# version: "3"

services:
  app:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    ports:
      - 127.0.0.1:8005:80
    environment:
      - TZ='Asia/Tehran'

    volumes:
      - /srv/gotify/data:/app/data
